<a href="https://colab.research.google.com/github/phmlehau/TH_DeepLearning/blob/main/Lap1_TH_DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [3]:
import numpy as np

# --- 3.1. Tạo array 1-chiều ---
# Cách 1: Chuyển list --> Numpy array
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

# Cách 2
a = np.array([1, 9, 15, 39])
print(a)

# Xem kích thước mảng, kiểu dữ liệu
print(a.shape)
print(a.dtype)

# --- 3.2. Array 2-chiều ---
c = np.array([(1, 2, 3), (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

# --- 3.3. Array 3-chiều ---
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])
print(d)
print(d.shape)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]
(4,)
int64
[[1 2 3]
 [4 5 6]]
(2, 3)
int64
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [4]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n', e)
print('One matrix:\n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# --- 3.5.1. Reshape thay đổi kích thước ma trận ---
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

# --- 3.5.2. Flatten chuyển array nhiều chiều về 1 chiều ---
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
j = g.flatten()
print(j)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [6]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
# --- 3.7.1. Sinh mảng số nguyên ngẫu nhiên ---
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

# --- 3.7.2. Sinh mảng số thực trong khoảng [0, 1] ---
a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

# --- 3.7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian ---
# loc: giá trị trung tâm, scale: độ lệch chuẩn, size: số phần tử
a = np.random.normal(5, 0.5, 10)
print(a)

# --- 3.7.4. Sinh ngẫu nhiên từ mảng giá trị cho trước ---
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

Random 1-D array
 [47 86 58 13 11]
Random 2-D array
 [[ 4  9  6 31]
 [82 27 52 55]
 [94 25 14 57]]
Random 3-D array
 [[[39 67 59]
  [81 76 82]
  [ 6 15 44]
  [18 45 96]]

 [[66 90 82]
  [22 59 61]
  [69 67 93]
  [74 91 64]]

 [[82 55 39]
  [10  6 27]
  [33 68 47]
  [28 34 23]]]
Random 1-D array
 [0.37921463 0.10692438 0.69764397 0.30239095 0.99569389]
Random 2-D array
 [[0.99652314 0.78163387 0.30790152 0.47497748]
 [0.51068014 0.82534833 0.52387471 0.90715565]
 [0.66677285 0.20186208 0.95247213 0.79089736]]
Random 3-D array
 [[[0.01026416 0.14770835 0.14378727]
  [0.7181696  0.24825202 0.48150729]
  [0.25543579 0.23500021 0.06716696]
  [0.04905471 0.52894366 0.65588572]]

 [[0.97919547 0.3231793  0.41692851]
  [0.40907982 0.07283026 0.73585934]
  [0.95388165 0.64083352 0.95216343]
  [0.61652312 0.73322447 0.9856461 ]]

 [[0.82032717 0.19829855 0.82226201]
  [0.65560911 0.91871089 0.69462193]
  [0.36911513 0.29365017 0.68633845]
  [0.46058812 0.17856094 0.56006163]]]
[4.772939   4.9995

In [8]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)

# Dùng array (không thay đổi ma trận gốc trực tiếp)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)

# Dùng asarray (thay đổi trực tiếp lên ma trận gốc)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
# --- 3.9.1. Dùng hàm arange ---
a = np.arange(1, 20)  # Tạo các số từ 1 đến 19
print(a)

b = np.arange(1, 20, 2)  # Mỗi bước tăng 2 giá trị
print(b)

# --- 3.9.2. Dùng hàm linspace ---
a = np.linspace(1., 5., num=10)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [10]:
# Quy tắc: trước dấu phẩy là dòng, sau dấu phẩy là cột. Dấu : để chọn toàn bộ dòng/cột.
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])

print('Second column:', a[:, 1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, 0:2]) # Chỉnh sửa từ bản gốc bị lỗi OCR lỗi in [1, 2] thành khoảng cắt đúng

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


In [2]:
pip install pandas

In [11]:
import pandas as pd

# Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])

# Tạo series với index tự đặt
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])

# Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [12]:

h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame: \n', df_h)

# Chuyển Pandas --> Numpy
numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)

# Tạo DataFrame mảng 2-chiều có tên cột từ Dictionary
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

# Tạo mảng ngẫu nhiên 20x4 và chuyển thành DataFrame có tên cột
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  # in 5 dòng đầu tiên

DataFrame: 
    0  1
0  1  2
1  3  4
Numpy array: 
 [[1 2]
 [3 4]]
    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0  0.391790  0.283191  1.164096  0.459613
1  1.245195 -0.074880  1.515714 -0.773468
2 -0.877717  1.871524  0.329253 -2.012033
3  0.755151  1.187648 -1.363253 -0.031810
4  0.668492  0.104114  0.262032  0.796569


In [22]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])

# ==========================================
# --- Lọc và xử lý trên DataFrame
# ==========================================
print("--- Hàng từ chỉ mục 1 đến 3 ---")
print(df[1:4])

print("\n--- Lọc so1 > 0 ---")
print(df[df['so1'] > 0])

df_drop = df.drop(columns=['so4'])
print("\n--- Sau khi xóa cột so4 ---")
print(df_drop.head())


# ==========================================
# --- Thao tác nối dữ liệu & Đổi tên cột
# ==========================================
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'], 'Age': [25, 30, 50]})
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'], 'Age': [28, 11]})

df_concat = pd.concat([df1, df2], ignore_index=True)
print("\nConcatenate Two DataFrames:\n", df_concat)

df_drop_dup = df_concat.drop_duplicates(subset=['Name'])
print("\nDrop duplicates:\n", df_drop_dup)

df_sorted = df_concat.sort_values(by='Age')
print("\nSort values:\n", df_sorted)

df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_Input'})
print("\nRename columns:\n", df_rename)


# ==========================================
# --- Đọc dữ liệu từ file CSV
# ==========================================
path = "patient_heart_rate.csv"
COLUMNS = ["Id", "Name", "Age", "Weight", "m0006", "m0612", "m1218", "f0006", "f0612", "f1218"]

try:
    df_csv = pd.read_csv(path, skipinitialspace=True, header=0, names=COLUMNS, index_col=False)
    print("\n--- Dữ liệu từ file patient_heart_rate.csv ---")
    print(df_csv.head())
    print("Kích thước file:", df_csv.shape)
except FileNotFoundError:
    print(f"\n[Lỗi] Không tìm thấy file '{path}'. Vui lòng upload file lên Colab.")


# ==========================================
# --- Gom nhóm dữ liệu - GroupBy
# ==========================================
try:
    df_fish = pd.read_csv("Fish.csv", skipinitialspace=True, index_col=False)

    print("\n--- Gom nhóm theo Species và tính trung bình ---")
    print(df_fish.groupby(['Species']).mean().head())

    print("\n--- Tính trung bình riêng cho cột 'Weight' ---")
    print(df_fish.groupby(['Species'])['Weight'].mean().head())
except FileNotFoundError:
    print("\n[Lưu ý] Không tìm thấy file 'Fish.csv' để chạy phần GroupBy.")

--- Hàng từ chỉ mục 1 đến 3 ---
        so1       so2       so3       so4
1 -2.107215  0.492174 -0.084190  0.567771
2 -0.433610 -0.895057 -0.718188 -0.795092
3 -0.697840 -0.875761  0.596212 -0.810797

--- Lọc so1 > 0 ---
         so1       so2       so3       so4
0   0.360278 -0.209913 -0.361583  0.505725
4   1.486933 -1.467676 -0.524754  0.964349
8   1.517775  0.663881 -0.281072  1.386763
9   0.626756 -0.263001  0.328492  1.285082
10  0.746760 -1.245483 -0.584912  0.278092
12  0.180049  0.305115  1.196596  0.305157
13  0.034101 -0.304949  0.863059 -3.360602
14  2.115568  0.494163  0.204561  0.095519
17  0.888532 -0.128748  0.452429 -0.904748

--- Sau khi xóa cột so4 ---
        so1       so2       so3
0  0.360278 -0.209913 -0.361583
1 -2.107215  0.492174 -0.084190
2 -0.433610 -0.895057 -0.718188
3 -0.697840 -0.875761  0.596212
4  1.486933 -1.467676 -0.524754

Concatenate Two DataFrames:
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   28
4  Smith   11

Drop duplicat